<?php

namespace Consilience\Xero\PayrollAuSdk\Model;

/**
 * EmploymentBasis
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team <team@openapitools.org>
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
use Consilience\Xero\PayrollAuSdk\ObjectSerializer;

/**
 * EmploymentBasis Class Doc Comment
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team <team@openapitools.org>
 * @link     https://openapi-generator.tech
 */
class EmploymentBasis
{
    /**
     * Possible values of this enum
     */
    const FULLTIME = 'FULLTIME';
    const PARTTIME = 'PARTTIME';
    const CASUAL = 'CASUAL';
    const LABOURHIRE = 'LABOURHIRE';
    const SUPERINCOMESTREAM = 'SUPERINCOMESTREAM';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FULLTIME,
            self::PARTTIME,
            self::CASUAL,
            self::LABOURHIRE,
            self::SUPERINCOMESTREAM,
        ];
    }
}
