<?php

namespace Consilience\Xero\PayrollAuSdk\Model;

/**
 * LeaveType
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team <team@openapitools.org>
 * @link     https://openapi-generator.tech
 */

/**
 * Payroll - AU
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

use ArrayAccess;
use JsonSerializable;
use Consilience\Xero\PayrollAuSdk\ObjectSerializer;

/**
 * LeaveType Class Doc Comment
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team <team@openapitools.org>
 * @link     https://openapi-generator.tech
 */
class LeaveType implements ModelInterface, ArrayAccess, JsonSerializable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LeaveType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'typeOfUnits' => 'float',
        'isPaidLeave' => 'string',
        'showOnPayslip' => 'string',
        'leaveTypeID' => 'string',
        'normalEntitlement' => 'string',
        'leaveLoadingRate' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'name' => null,
        'typeOfUnits' => 'float',
        'isPaidLeave' => null,
        'showOnPayslip' => null,
        'leaveTypeID' => 'uuid',
        'normalEntitlement' => null,
        'leaveLoadingRate' => 'float'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Attributes of form: local name => original name
     * Local name is camelCase, original name is as per API description
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'typeOfUnits' => 'TypeOfUnits',
        'isPaidLeave' => 'IsPaidLeave',
        'showOnPayslip' => 'ShowOnPayslip',
        'leaveTypeID' => 'LeaveTypeID',
        'normalEntitlement' => 'NormalEntitlement',
        'leaveLoadingRate' => 'LeaveLoadingRate'
    ];

    /**
     * Attributes to setter functions
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'typeOfUnits' => 'setTypeOfUnits',
        'isPaidLeave' => 'setIsPaidLeave',
        'showOnPayslip' => 'setShowOnPayslip',
        'leaveTypeID' => 'setLeaveTypeID',
        'normalEntitlement' => 'setNormalEntitlement',
        'leaveLoadingRate' => 'setLeaveLoadingRate'
    ];

    /**
     * Array of attributes to getter functions
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'typeOfUnits' => 'getTypeOfUnits',
        'isPaidLeave' => 'getIsPaidLeave',
        'showOnPayslip' => 'getShowOnPayslip',
        'leaveTypeID' => 'getLeaveTypeID',
        'normalEntitlement' => 'getNormalEntitlement',
        'leaveLoadingRate' => 'getLeaveLoadingRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to accessor functions
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = $data['name'] ?? null;
        $this->container['typeOfUnits'] = $data['typeOfUnits'] ?? null;
        $this->container['isPaidLeave'] = $data['isPaidLeave'] ?? null;
        $this->container['showOnPayslip'] = $data['showOnPayslip'] ?? null;
        $this->container['leaveTypeID'] = $data['leaveTypeID'] ?? null;
        $this->container['normalEntitlement'] = $data['normalEntitlement'] ?? null;
        $this->container['leaveLoadingRate'] = $data['leaveLoadingRate'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = sprintf('"%s" can\'t be null', 'name');
        }
        if ((mb_strlen($this->container['name']) > 50)) {
            $invalidProperties[] = sprintf(
                'invalid value for "%s", the character length must be smaller than or equal to %d.',
                'name',
                50
            );
        }

        if ($this->container['typeOfUnits'] === null) {
            $invalidProperties[] = sprintf('"%s" can\'t be null', 'typeOfUnits');
        }
        if ($this->container['isPaidLeave'] === null) {
            $invalidProperties[] = sprintf('"%s" can\'t be null', 'isPaidLeave');
        }
        if ($this->container['showOnPayslip'] === null) {
            $invalidProperties[] = sprintf('"%s" can\'t be null', 'showOnPayslip');
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->get('name');
    }

    /**
     * Sets name
     *
     * @param string $name Name of the leave type (max length = 50)
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((mb_strlen($name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $name when calling LeaveType., must be smaller than or equal to 50.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets typeOfUnits
     *
     * @return float
     */
    public function getTypeOfUnits()
    {
        return $this->get('typeOfUnits');
    }

    /**
     * Sets typeOfUnits
     *
     * @param float $typeOfUnits The type of units by which leave entitlements are normally tracked. These are typically the same as the type of units used for the employee’s ordinary earnings rate
     *
     * @return $this
     */
    public function setTypeOfUnits($typeOfUnits)
    {
        $this->container['typeOfUnits'] = $typeOfUnits;

        return $this;
    }

    /**
     * Gets isPaidLeave
     *
     * @return string
     */
    public function getIsPaidLeave()
    {
        return $this->get('isPaidLeave');
    }

    /**
     * Sets isPaidLeave
     *
     * @param string $isPaidLeave Set this to indicate that an employee will be paid when taking this type of leave
     *
     * @return $this
     */
    public function setIsPaidLeave($isPaidLeave)
    {
        $this->container['isPaidLeave'] = $isPaidLeave;

        return $this;
    }

    /**
     * Gets showOnPayslip
     *
     * @return string
     */
    public function getShowOnPayslip()
    {
        return $this->get('showOnPayslip');
    }

    /**
     * Sets showOnPayslip
     *
     * @param string $showOnPayslip Set this if you want a balance for this leave type to be shown on your employee’s payslips
     *
     * @return $this
     */
    public function setShowOnPayslip($showOnPayslip)
    {
        $this->container['showOnPayslip'] = $showOnPayslip;

        return $this;
    }

    /**
     * Gets leaveTypeID
     *
     * @return string|null
     */
    public function getLeaveTypeID()
    {
        return $this->get('leaveTypeID');
    }

    /**
     * Sets leaveTypeID
     *
     * @param string|null $leaveTypeID Xero identifier
     *
     * @return $this
     */
    public function setLeaveTypeID($leaveTypeID)
    {
        $this->container['leaveTypeID'] = $leaveTypeID;

        return $this;
    }

    /**
     * Gets normalEntitlement
     *
     * @return string|null
     */
    public function getNormalEntitlement()
    {
        return $this->get('normalEntitlement');
    }

    /**
     * Sets normalEntitlement
     *
     * @param string|null $normalEntitlement The number of units the employee is entitled to each year
     *
     * @return $this
     */
    public function setNormalEntitlement($normalEntitlement)
    {
        $this->container['normalEntitlement'] = $normalEntitlement;

        return $this;
    }

    /**
     * Gets leaveLoadingRate
     *
     * @return float|null
     */
    public function getLeaveLoadingRate()
    {
        return $this->get('leaveLoadingRate');
    }

    /**
     * Sets leaveLoadingRate
     *
     * @param float|null $leaveLoadingRate Enter an amount here if your organisation pays an additional percentage on top of ordinary earnings when your employees take leave (typically 17.5%)
     *
     * @return $this
     */
    public function setLeaveLoadingRate($leaveLoadingRate)
    {
        $this->container['leaveLoadingRate'] = $leaveLoadingRate;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode($this, JSON_PRETTY_PRINT);
    }

    /**
     * Convert to a nested array.
     * This is not an ideal method, and needs to be revisited.
     *
     * @return array
     */
    public function toArray()
    {
        return json_decode(json_encode($this), true);
    }

    /**
     * Return the JSON serialisable data for this model.
     *
     * @return string|object
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Return a property value.
     *
     * @param string $name    Name of the property
     * @param mixed  $default Value if property is not set
     *
     * @return mixed
     */
    public function get(string $name, $default = null)
    {
        return $this->container[$name] ?? $default;
    }

    /**
     * Hangle magic getter to return properties.
     *
     * @param string $name Name of the property
     *
     * @return mixed
     */
    public function __get($name)
    {
        return $this->get($name);
    }
}
