<?php

namespace Consilience\Xero\PayrollAuSdk\Model;

/**
 * Payrun
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team <team@openapitools.org>
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

use ArrayAccess;
use JsonSerializable;
use Consilience\Xero\PayrollAuSdk\ObjectSerializer;

/**
 * Payrun Class Doc Comment
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team <team@openapitools.org>
 * @link     https://openapi-generator.tech
 */
class Payrun implements ModelInterface, ArrayAccess, JsonSerializable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Payrun';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payrollCalendarID' => 'object',
        'payRunID' => 'object',
        'payRunPeriodStartDate' => '\DateTime',
        'payRunPeriodEndDate' => '\DateTime',
        'payRunStatus' => '\Consilience\Xero\PayrollAuSdk\Model\PayRunStatus',
        'paymentDate' => '\DateTime',
        'payslipMessage' => 'string',
        'updatedDateUTC' => '\DateTime',
        'payslips' => '\Consilience\Xero\PayrollAuSdk\Model\PayslipSummary[]',
        'wages' => 'float',
        'deductions' => 'float',
        'tax' => 'float',
        'super' => 'float',
        'reimbursements' => 'float',
        'netPay' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'payrollCalendarID' => 'uuid',
        'payRunID' => 'uuid',
        'payRunPeriodStartDate' => 'date',
        'payRunPeriodEndDate' => 'date',
        'payRunStatus' => null,
        'paymentDate' => 'date',
        'payslipMessage' => null,
        'updatedDateUTC' => 'date-time',
        'payslips' => null,
        'wages' => 'float',
        'deductions' => 'float',
        'tax' => 'float',
        'super' => 'float',
        'reimbursements' => 'float',
        'netPay' => 'float'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Attributes of form: local name => original name
     * Local name is camelCase, original name is as per API description
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payrollCalendarID' => 'PayrollCalendarID',
        'payRunID' => 'PayRunID',
        'payRunPeriodStartDate' => 'PayRunPeriodStartDate',
        'payRunPeriodEndDate' => 'PayRunPeriodEndDate',
        'payRunStatus' => 'PayRunStatus',
        'paymentDate' => 'PaymentDate',
        'payslipMessage' => 'PayslipMessage',
        'updatedDateUTC' => 'UpdatedDateUTC',
        'payslips' => 'Payslips',
        'wages' => 'Wages',
        'deductions' => 'Deductions',
        'tax' => 'Tax',
        'super' => 'Super',
        'reimbursements' => 'Reimbursements',
        'netPay' => 'NetPay'
    ];

    /**
     * Attributes to setter functions
     *
     * @var string[]
     */
    protected static $setters = [
        'payrollCalendarID' => 'setPayrollCalendarID',
        'payRunID' => 'setPayRunID',
        'payRunPeriodStartDate' => 'setPayRunPeriodStartDate',
        'payRunPeriodEndDate' => 'setPayRunPeriodEndDate',
        'payRunStatus' => 'setPayRunStatus',
        'paymentDate' => 'setPaymentDate',
        'payslipMessage' => 'setPayslipMessage',
        'updatedDateUTC' => 'setUpdatedDateUTC',
        'payslips' => 'setPayslips',
        'wages' => 'setWages',
        'deductions' => 'setDeductions',
        'tax' => 'setTax',
        'super' => 'setSuper',
        'reimbursements' => 'setReimbursements',
        'netPay' => 'setNetPay'
    ];

    /**
     * Array of attributes to getter functions
     *
     * @var string[]
     */
    protected static $getters = [
        'payrollCalendarID' => 'getPayrollCalendarID',
        'payRunID' => 'getPayRunID',
        'payRunPeriodStartDate' => 'getPayRunPeriodStartDate',
        'payRunPeriodEndDate' => 'getPayRunPeriodEndDate',
        'payRunStatus' => 'getPayRunStatus',
        'paymentDate' => 'getPaymentDate',
        'payslipMessage' => 'getPayslipMessage',
        'updatedDateUTC' => 'getUpdatedDateUTC',
        'payslips' => 'getPayslips',
        'wages' => 'getWages',
        'deductions' => 'getDeductions',
        'tax' => 'getTax',
        'super' => 'getSuper',
        'reimbursements' => 'getReimbursements',
        'netPay' => 'getNetPay'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to accessor functions
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['payrollCalendarID'] = $data['payrollCalendarID'] ?? null;
        $this->container['payRunID'] = $data['payRunID'] ?? null;
        $this->container['payRunPeriodStartDate'] = $data['payRunPeriodStartDate'] ?? null;
        $this->container['payRunPeriodEndDate'] = $data['payRunPeriodEndDate'] ?? null;
        $this->container['payRunStatus'] = $data['payRunStatus'] ?? null;
        $this->container['paymentDate'] = $data['paymentDate'] ?? null;
        $this->container['payslipMessage'] = $data['payslipMessage'] ?? null;
        $this->container['updatedDateUTC'] = $data['updatedDateUTC'] ?? null;
        $this->container['payslips'] = $data['payslips'] ?? null;
        $this->container['wages'] = $data['wages'] ?? null;
        $this->container['deductions'] = $data['deductions'] ?? null;
        $this->container['tax'] = $data['tax'] ?? null;
        $this->container['super'] = $data['super'] ?? null;
        $this->container['reimbursements'] = $data['reimbursements'] ?? null;
        $this->container['netPay'] = $data['netPay'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['payrollCalendarID'] === null) {
            $invalidProperties[] = sprintf('"%s" can\'t be null', 'payrollCalendarID');
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payrollCalendarID
     *
     * @return object
     */
    public function getPayrollCalendarID()
    {
        return $this->get('payrollCalendarID');
    }

    /**
     * Sets payrollCalendarID
     *
     * @param object $payrollCalendarID Xero identifier for pay run
     *
     * @return $this
     */
    public function setPayrollCalendarID($payrollCalendarID)
    {
        $this->container['payrollCalendarID'] = $payrollCalendarID;

        return $this;
    }

    /**
     * Gets payRunID
     *
     * @return object|null
     */
    public function getPayRunID()
    {
        return $this->get('payRunID');
    }

    /**
     * Sets payRunID
     *
     * @param object|null $payRunID Xero identifier for pay run
     *
     * @return $this
     */
    public function setPayRunID($payRunID)
    {
        $this->container['payRunID'] = $payRunID;

        return $this;
    }

    /**
     * Gets payRunPeriodStartDate
     *
     * @return \DateTime|null
     */
    public function getPayRunPeriodStartDate()
    {
        return $this->get('payRunPeriodStartDate');
    }

    /**
     * Sets payRunPeriodStartDate
     *
     * @param \DateTime|null $payRunPeriodStartDate Period Start Date for the PayRun (YYYY-MM-DD)
     *
     * @return $this
     */
    public function setPayRunPeriodStartDate($payRunPeriodStartDate)
    {
        $this->container['payRunPeriodStartDate'] = $payRunPeriodStartDate;

        return $this;
    }

    /**
     * Gets payRunPeriodEndDate
     *
     * @return \DateTime|null
     */
    public function getPayRunPeriodEndDate()
    {
        return $this->get('payRunPeriodEndDate');
    }

    /**
     * Sets payRunPeriodEndDate
     *
     * @param \DateTime|null $payRunPeriodEndDate Period End Date for the PayRun (YYYY-MM-DD)
     *
     * @return $this
     */
    public function setPayRunPeriodEndDate($payRunPeriodEndDate)
    {
        $this->container['payRunPeriodEndDate'] = $payRunPeriodEndDate;

        return $this;
    }

    /**
     * Gets payRunStatus
     *
     * @return \Consilience\Xero\PayrollAuSdk\Model\PayRunStatus|null
     */
    public function getPayRunStatus()
    {
        return $this->get('payRunStatus');
    }

    /**
     * Sets payRunStatus
     *
     * @param \Consilience\Xero\PayrollAuSdk\Model\PayRunStatus|null $payRunStatus payRunStatus
     *
     * @return $this
     */
    public function setPayRunStatus($payRunStatus)
    {
        $this->container['payRunStatus'] = $payRunStatus;

        return $this;
    }

    /**
     * Gets paymentDate
     *
     * @return \DateTime|null
     */
    public function getPaymentDate()
    {
        return $this->get('paymentDate');
    }

    /**
     * Sets paymentDate
     *
     * @param \DateTime|null $paymentDate Payment Date for the PayRun (YYYY-MM-DD)
     *
     * @return $this
     */
    public function setPaymentDate($paymentDate)
    {
        $this->container['paymentDate'] = $paymentDate;

        return $this;
    }

    /**
     * Gets payslipMessage
     *
     * @return string|null
     */
    public function getPayslipMessage()
    {
        return $this->get('payslipMessage');
    }

    /**
     * Sets payslipMessage
     *
     * @param string|null $payslipMessage Payslip message for the PayRun
     *
     * @return $this
     */
    public function setPayslipMessage($payslipMessage)
    {
        $this->container['payslipMessage'] = $payslipMessage;

        return $this;
    }

    /**
     * Gets updatedDateUTC
     *
     * @return \DateTime|null
     */
    public function getUpdatedDateUTC()
    {
        return $this->get('updatedDateUTC');
    }

    /**
     * Sets updatedDateUTC
     *
     * @param \DateTime|null $updatedDateUTC Last modified timestamp
     *
     * @return $this
     */
    public function setUpdatedDateUTC($updatedDateUTC)
    {
        $this->container['updatedDateUTC'] = $updatedDateUTC;

        return $this;
    }

    /**
     * Gets payslips
     *
     * @return \Consilience\Xero\PayrollAuSdk\Model\PayslipSummary[]|null
     */
    public function getPayslips()
    {
        return $this->get('payslips');
    }

    /**
     * Sets payslips
     *
     * @param \Consilience\Xero\PayrollAuSdk\Model\PayslipSummary[]|null $payslips The payslips in the payrun
     *
     * @return $this
     */
    public function setPayslips($payslips)
    {
        $this->container['payslips'] = $payslips;

        return $this;
    }

    /**
     * Gets wages
     *
     * @return float|null
     */
    public function getWages()
    {
        return $this->get('wages');
    }

    /**
     * Sets wages
     *
     * @param float|null $wages The total Wages for the Payrun
     *
     * @return $this
     */
    public function setWages($wages)
    {
        $this->container['wages'] = $wages;

        return $this;
    }

    /**
     * Gets deductions
     *
     * @return float|null
     */
    public function getDeductions()
    {
        return $this->get('deductions');
    }

    /**
     * Sets deductions
     *
     * @param float|null $deductions The total Deductions for the Payrun
     *
     * @return $this
     */
    public function setDeductions($deductions)
    {
        $this->container['deductions'] = $deductions;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return float|null
     */
    public function getTax()
    {
        return $this->get('tax');
    }

    /**
     * Sets tax
     *
     * @param float|null $tax The total Tax for the Payrun
     *
     * @return $this
     */
    public function setTax($tax)
    {
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets super
     *
     * @return float|null
     */
    public function getSuper()
    {
        return $this->get('super');
    }

    /**
     * Sets super
     *
     * @param float|null $super The total Super for the Payrun
     *
     * @return $this
     */
    public function setSuper($super)
    {
        $this->container['super'] = $super;

        return $this;
    }

    /**
     * Gets reimbursements
     *
     * @return float|null
     */
    public function getReimbursements()
    {
        return $this->get('reimbursements');
    }

    /**
     * Sets reimbursements
     *
     * @param float|null $reimbursements The total Reimbursements for the Payrun
     *
     * @return $this
     */
    public function setReimbursements($reimbursements)
    {
        $this->container['reimbursements'] = $reimbursements;

        return $this;
    }

    /**
     * Gets netPay
     *
     * @return float|null
     */
    public function getNetPay()
    {
        return $this->get('netPay');
    }

    /**
     * Sets netPay
     *
     * @param float|null $netPay The total NetPay for the Payrun
     *
     * @return $this
     */
    public function setNetPay($netPay)
    {
        $this->container['netPay'] = $netPay;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode($this, JSON_PRETTY_PRINT);
    }

    /**
     * Convert to a nested array.
     * This is not an ideal method, and needs to be revisited.
     *
     * @return array
     */
    public function toArray()
    {
        return json_decode(json_encode($this), true);
    }

    /**
     * Return the JSON serialisable data for this model.
     *
     * @return string|object
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Return a property value.
     *
     * @param string $name    Name of the property
     * @param mixed  $default Value if property is not set
     *
     * @return mixed
     */
    public function get(string $name, $default = null)
    {
        return $this->container[$name] ?? $default;
    }

    /**
     * Hangle magic getter to return properties.
     *
     * @param string $name Name of the property
     *
     * @return mixed
     */
    public function __get($name)
    {
        return $this->get($name);
    }
}
