<?php

namespace Consilience\Xero\AccountingSdk;

/**
 * SalesTrackingCategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\AccountingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * SalesTrackingCategoryTest Class Doc Comment
 *
 * @category    Class
 * @description SalesTrackingCategory
 * @package     Consilience\Xero\AccountingSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SalesTrackingCategoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesTrackingCategory"
     */
    public function testSalesTrackingCategory()
    {
    }

    /**
     * Test attribute "trackingCategoryName"
     */
    public function testPropertyTrackingCategoryName()
    {
    }

    /**
     * Test attribute "trackingOptionName"
     */
    public function testPropertyTrackingOptionName()
    {
    }
}
