<?php

namespace Consilience\Xero\AccountingSdk;

/**
 * ScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\AccountingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * ScheduleTest Class Doc Comment
 *
 * @category    Class
 * @description Schedule
 * @package     Consilience\Xero\AccountingSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScheduleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Schedule"
     */
    public function testSchedule()
    {
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "dueDate"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "dueDateType"
     */
    public function testPropertyDueDateType()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "nextScheduledDate"
     */
    public function testPropertyNextScheduledDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }
}
