<?php

namespace Consilience\FooBar;

/**
 * AssetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\FooBar
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Assets API
 *
 * This the Xero Assets API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * AssetTest Class Doc Comment
 *
 * @category    Class
 * @description Asset
 * @package     Consilience\FooBar
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AssetTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Asset"
     */
    public function testAsset()
    {
    }

    /**
     * Test attribute "assetId"
     */
    public function testPropertyAssetId()
    {
    }

    /**
     * Test attribute "assetName"
     */
    public function testPropertyAssetName()
    {
    }

    /**
     * Test attribute "assetNumber"
     */
    public function testPropertyAssetNumber()
    {
    }

    /**
     * Test attribute "purchaseDate"
     */
    public function testPropertyPurchaseDate()
    {
    }

    /**
     * Test attribute "purchasePrice"
     */
    public function testPropertyPurchasePrice()
    {
    }

    /**
     * Test attribute "disposalPrice"
     */
    public function testPropertyDisposalPrice()
    {
    }

    /**
     * Test attribute "assetStatus"
     */
    public function testPropertyAssetStatus()
    {
    }

    /**
     * Test attribute "warrantyExpiryDate"
     */
    public function testPropertyWarrantyExpiryDate()
    {
    }

    /**
     * Test attribute "serialNumber"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "bookDepreciationSetting"
     */
    public function testPropertyBookDepreciationSetting()
    {
    }

    /**
     * Test attribute "bookDepreciationDetail"
     */
    public function testPropertyBookDepreciationDetail()
    {
    }

    /**
     * Test attribute "canRollBack"
     */
    public function testPropertyCanRollBack()
    {
    }

    /**
     * Test attribute "accountingBookValue"
     */
    public function testPropertyAccountingBookValue()
    {
    }
}
