<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * EarningsLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payroll - AU
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * EarningsLineTest Class Doc Comment
 *
 * @category    Class
 * @description EarningsLine
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EarningsLineTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EarningsLine"
     */
    public function testEarningsLine()
    {
    }

    /**
     * Test attribute "earningsRateID"
     */
    public function testPropertyEarningsRateID()
    {
    }

    /**
     * Test attribute "ratePerUnit"
     */
    public function testPropertyRatePerUnit()
    {
    }

    /**
     * Test attribute "numberOfUnits"
     */
    public function testPropertyNumberOfUnits()
    {
    }

    /**
     * Test attribute "fixedAmount"
     */
    public function testPropertyFixedAmount()
    {
    }
}
