<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * EmployeeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payroll - AU
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * EmployeeTest Class Doc Comment
 *
 * @category    Class
 * @description Employee
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EmployeeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Employee"
     */
    public function testEmployee()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "dateOfBirth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "homeAddress"
     */
    public function testPropertyHomeAddress()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "middleNames"
     */
    public function testPropertyMiddleNames()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "twitterUserName"
     */
    public function testPropertyTwitterUserName()
    {
    }

    /**
     * Test attribute "isAuthorisedToApproveLeave"
     */
    public function testPropertyIsAuthorisedToApproveLeave()
    {
    }

    /**
     * Test attribute "isAuthorisedToApproveTimesheets"
     */
    public function testPropertyIsAuthorisedToApproveTimesheets()
    {
    }

    /**
     * Test attribute "jobTitle"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "classification"
     */
    public function testPropertyClassification()
    {
    }

    /**
     * Test attribute "ordinaryEarningsRateID"
     */
    public function testPropertyOrdinaryEarningsRateID()
    {
    }

    /**
     * Test attribute "payrollCalendarID"
     */
    public function testPropertyPayrollCalendarID()
    {
    }

    /**
     * Test attribute "employeeGroupName"
     */
    public function testPropertyEmployeeGroupName()
    {
    }

    /**
     * Test attribute "bankAccounts"
     */
    public function testPropertyBankAccounts()
    {
    }

    /**
     * Test attribute "payTemplate"
     */
    public function testPropertyPayTemplate()
    {
    }

    /**
     * Test attribute "openingBalances"
     */
    public function testPropertyOpeningBalances()
    {
    }

    /**
     * Test attribute "leaveBalances"
     */
    public function testPropertyLeaveBalances()
    {
    }

    /**
     * Test attribute "superMemberships"
     */
    public function testPropertySuperMemberships()
    {
    }

    /**
     * Test attribute "terminationDate"
     */
    public function testPropertyTerminationDate()
    {
    }

    /**
     * Test attribute "employeeID"
     */
    public function testPropertyEmployeeID()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "updatedDateUTC"
     */
    public function testPropertyUpdatedDateUTC()
    {
    }
}
