<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * PayRunTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payroll - AU
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * PayRunTest Class Doc Comment
 *
 * @category    Class
 * @description PayRun
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PayRunTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayRun"
     */
    public function testPayRun()
    {
    }

    /**
     * Test attribute "payrollCalendarID"
     */
    public function testPropertyPayrollCalendarID()
    {
    }

    /**
     * Test attribute "payRunID"
     */
    public function testPropertyPayRunID()
    {
    }

    /**
     * Test attribute "payRunPeriodStartDate"
     */
    public function testPropertyPayRunPeriodStartDate()
    {
    }

    /**
     * Test attribute "payRunPeriodEndDate"
     */
    public function testPropertyPayRunPeriodEndDate()
    {
    }

    /**
     * Test attribute "payRunStatus"
     */
    public function testPropertyPayRunStatus()
    {
    }

    /**
     * Test attribute "paymentDate"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "payslipMessage"
     */
    public function testPropertyPayslipMessage()
    {
    }

    /**
     * Test attribute "payslips"
     */
    public function testPropertyPayslips()
    {
    }

    /**
     * Test attribute "wages"
     */
    public function testPropertyWages()
    {
    }

    /**
     * Test attribute "deductions"
     */
    public function testPropertyDeductions()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "super"
     */
    public function testPropertySuper()
    {
    }

    /**
     * Test attribute "reimbursement"
     */
    public function testPropertyReimbursement()
    {
    }

    /**
     * Test attribute "netPay"
     */
    public function testPropertyNetPay()
    {
    }
}
