<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * PayTemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payroll - AU
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * PayTemplateTest Class Doc Comment
 *
 * @category    Class
 * @description PayTemplate
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PayTemplateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayTemplate"
     */
    public function testPayTemplate()
    {
    }

    /**
     * Test attribute "earningsLines"
     */
    public function testPropertyEarningsLines()
    {
    }

    /**
     * Test attribute "deductionLines"
     */
    public function testPropertyDeductionLines()
    {
    }

    /**
     * Test attribute "superLines"
     */
    public function testPropertySuperLines()
    {
    }

    /**
     * Test attribute "reimbursementLines"
     */
    public function testPropertyReimbursementLines()
    {
    }

    /**
     * Test attribute "leaveLines"
     */
    public function testPropertyLeaveLines()
    {
    }

    /**
     * Test attribute "earningsRateID"
     */
    public function testPropertyEarningsRateID()
    {
    }

    /**
     * Test attribute "calculationType"
     */
    public function testPropertyCalculationType()
    {
    }

    /**
     * Test attribute "numberOfUnitsPerWeek"
     */
    public function testPropertyNumberOfUnitsPerWeek()
    {
    }

    /**
     * Test attribute "annualSalary"
     */
    public function testPropertyAnnualSalary()
    {
    }

    /**
     * Test attribute "ratePerUnit"
     */
    public function testPropertyRatePerUnit()
    {
    }

    /**
     * Test attribute "normalNumberOfUnits"
     */
    public function testPropertyNormalNumberOfUnits()
    {
    }

    /**
     * Test attribute "deductionTypeID"
     */
    public function testPropertyDeductionTypeID()
    {
    }

    /**
     * Test attribute "percentage"
     */
    public function testPropertyPercentage()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "superMembershipID"
     */
    public function testPropertySuperMembershipID()
    {
    }

    /**
     * Test attribute "contributionType"
     */
    public function testPropertyContributionType()
    {
    }

    /**
     * Test attribute "expenseAccountCode"
     */
    public function testPropertyExpenseAccountCode()
    {
    }

    /**
     * Test attribute "liabilityAccountCode"
     */
    public function testPropertyLiabilityAccountCode()
    {
    }

    /**
     * Test attribute "minimumMonthlyEarnings"
     */
    public function testPropertyMinimumMonthlyEarnings()
    {
    }

    /**
     * Test attribute "reimbursementTypeID"
     */
    public function testPropertyReimbursementTypeID()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "leaveTypeID"
     */
    public function testPropertyLeaveTypeID()
    {
    }

    /**
     * Test attribute "annualNumberOfUnits"
     */
    public function testPropertyAnnualNumberOfUnits()
    {
    }

    /**
     * Test attribute "fullTimeNumberOfUnitsPerPeriod"
     */
    public function testPropertyFullTimeNumberOfUnitsPerPeriod()
    {
    }

    /**
     * Test attribute "numberOfUnits"
     */
    public function testPropertyNumberOfUnits()
    {
    }

    /**
     * Test attribute "entitlementFinalPayPayoutType"
     */
    public function testPropertyEntitlementFinalPayPayoutType()
    {
    }
}
