<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * SettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * SettingsTest Class Doc Comment
 *
 * @category    Class
 * @description Settings
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Settings"
     */
    public function testSettings()
    {
    }

    /**
     * Test attribute "accounts"
     */
    public function testPropertyAccounts()
    {
    }

    /**
     * Test attribute "trackingCategories"
     */
    public function testPropertyTrackingCategories()
    {
    }

    /**
     * Test attribute "daysInPayrollYear"
     */
    public function testPropertyDaysInPayrollYear()
    {
    }
}
