<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * SuperLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * SuperLineTest Class Doc Comment
 *
 * @category    Class
 * @description SuperLine
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SuperLineTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SuperLine"
     */
    public function testSuperLine()
    {
    }

    /**
     * Test attribute "superMembershipID"
     */
    public function testPropertySuperMembershipID()
    {
    }

    /**
     * Test attribute "contributionType"
     */
    public function testPropertyContributionType()
    {
    }

    /**
     * Test attribute "calculationType"
     */
    public function testPropertyCalculationType()
    {
    }

    /**
     * Test attribute "minimumMonthlyEarnings"
     */
    public function testPropertyMinimumMonthlyEarnings()
    {
    }

    /**
     * Test attribute "expenseAccountCode"
     */
    public function testPropertyExpenseAccountCode()
    {
    }

    /**
     * Test attribute "liabilityAccountCode"
     */
    public function testPropertyLiabilityAccountCode()
    {
    }

    /**
     * Test attribute "percentage"
     */
    public function testPropertyPercentage()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }
}
