<?php

namespace Consilience\Xero\PayrollAuSdk;

/**
 * SuperMembershipTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\PayrollAuSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payroll - AU
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * SuperMembershipTest Class Doc Comment
 *
 * @category    Class
 * @description SuperMembership
 * @package     Consilience\Xero\PayrollAuSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SuperMembershipTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SuperMembership"
     */
    public function testSuperMembership()
    {
    }

    /**
     * Test attribute "superFundID"
     */
    public function testPropertySuperFundID()
    {
    }

    /**
     * Test attribute "employeeNumber"
     */
    public function testPropertyEmployeeNumber()
    {
    }

    /**
     * Test attribute "superMembershipID"
     */
    public function testPropertySuperMembershipID()
    {
    }

    /**
     * Test attribute "employeeID"
     */
    public function testPropertyEmployeeID()
    {
    }
}
