<?php

namespace Consilience\Xero\FilesSdk;

/**
 * FilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\FilesSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Files API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

use \Consilience\Xero\FilesSdk\Configuration;
use \Consilience\Xero\FilesSdk\ApiException;
use \Consilience\Xero\FilesSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Consilience\Xero\FilesSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createFileAssociation
     *
     * create a new association.
     *
     */
    public function testCreateFileAssociation()
    {
    }

    /**
     * Test case for createFolder
     *
     * create a new folder.
     *
     */
    public function testCreateFolder()
    {
    }

    /**
     * Test case for deleteFile
     *
     * delete a file.
     *
     */
    public function testDeleteFile()
    {
    }

    /**
     * Test case for deleteFileAssociation
     *
     * create a new association.
     *
     */
    public function testDeleteFileAssociation()
    {
    }

    /**
     * Test case for deleteFolder
     *
     * delete a folder.
     *
     */
    public function testDeleteFolder()
    {
    }

    /**
     * Test case for getAssociationsByObject
     *
     * searches files.
     *
     */
    public function testGetAssociationsByObject()
    {
    }

    /**
     * Test case for getFile
     *
     * searches for file by unique id.
     *
     */
    public function testGetFile()
    {
    }

    /**
     * Test case for getFileAssociations
     *
     * searches files.
     *
     */
    public function testGetFileAssociations()
    {
    }

    /**
     * Test case for getFileContent
     *
     * searches files to retrieve the data.
     *
     */
    public function testGetFileContent()
    {
    }

    /**
     * Test case for getFiles
     *
     * searches files.
     *
     */
    public function testGetFiles()
    {
    }

    /**
     * Test case for getFolder
     *
     * searches specific folder by id.
     *
     */
    public function testGetFolder()
    {
    }

    /**
     * Test case for getFolders
     *
     * searches folder.
     *
     */
    public function testGetFolders()
    {
    }

    /**
     * Test case for getInbox
     *
     * searches inbox folder.
     *
     */
    public function testGetInbox()
    {
    }

    /**
     * Test case for updateFile
     *
     * Update a file.
     *
     */
    public function testUpdateFile()
    {
    }

    /**
     * Test case for updateFolder
     *
     * update folder.
     *
     */
    public function testUpdateFolder()
    {
    }

    /**
     * Test case for uploadFile
     *
     * upload an File.
     *
     */
    public function testUploadFile()
    {
    }
}
