<?php

namespace Consilience\Xero\FilesSdk;

/**
 * AssociationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Consilience\Xero\FilesSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Files API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * AssociationTest Class Doc Comment
 *
 * @category    Class
 * @description Association
 * @package     Consilience\Xero\FilesSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AssociationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Association"
     */
    public function testAssociation()
    {
    }

    /**
     * Test attribute "fileId"
     */
    public function testPropertyFileId()
    {
    }

    /**
     * Test attribute "objectId"
     */
    public function testPropertyObjectId()
    {
    }

    /**
     * Test attribute "objectGroup"
     */
    public function testPropertyObjectGroup()
    {
    }

    /**
     * Test attribute "objectType"
     */
    public function testPropertyObjectType()
    {
    }
}
